noremap i :colorscheme blue<cr>i
noremap o :colorscheme blue<cr>o
noremap s :colorscheme blue<cr>s
noremap a :colorscheme blue<cr>a
noremap I :colorscheme blue<cr>I
noremap O :colorscheme blue<cr>O
noremap S :colorscheme blue<cr>S
noremap A :colorscheme blue<cr>A
inoremap <Esc> <Esc>:colorscheme torte<cr> 
